name: Test packages/kysely-tailordb

on: workflow_call

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ./package.json
          registry-url: https://registry.npmjs.org

      - name: Setup pnpm
        run: |
          npm i -g corepack@latest
          corepack enable

      - name: Install deps
        working-directory: packages/kysely-tailordb
        run: |
          pnpm install

      - name: Lint
        working-directory: packages/kysely-tailordb
        run: |
          pnpm run check

      - name: Run type-check
        working-directory: packages/kysely-tailordb
        run: |
          pnpm run type-check

      - name: Build
        working-directory: packages/kysely-tailordb
        run: |
          pnpm run build
